[package]
name = "lfm-rs"
version = "0.1.0"
edition = "2024"
description = "A lightweight inference engine for Liquid Foundation Models (LFM), made with Rust"
license = "MIT"
readme = "README.md"

[dependencies]
burn = { version = "0.21.0", features = ["ndarray", "wgpu", "vulkan", "rocm"] }
burn-store = { version = "0.21.0", features = ["safetensors", "std"] }
bytemuck = "1.25.0"
memmap2 = "0.9.10"
safetensors = "0.7.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tokenizers = "0.23.1"
tokio = { version = "1.52.3", features = ["rt", "rt-multi-thread", "macros"] }

[dev-dependencies]
hf-hub = "0.4"

[patch.crates-io]
cubecl-hip-sys = { path = "../cubecl-hip/crates/cubecl-hip-sys" }
